### ISSUE TITLE
Should external contributions be sent to the external branch?

### ISSUE THREAD

**Issue by rootulp** [ElrondNetwork/docs.elrond.com#108]
> external contributions will be made to the external branch.

Sourced from the README

However the external branch is 180 commits behind master. Is external still recommended for external contributors, or is it okay if my PRs target master?

**Comment by bogdan-rosianu** [comment]
Hello!
Yes, the `external` branch should be used for external contributions. We have aligned the `external` branch meanwhile

**Comment by rootulp** [comment]
Sounds good! Thanks for clarifying. This issue can be closed.
