### ISSUE TITLE
Misleading chain id in erdpy config

### ISSUE THREAD

**Issue by MWFIAE** [ElrondNetwork/docs.elrond.com#137]
Hi!

Somebody asked me today what the chain id is, because the docs are very misleading. 

https://docs.elrond.com/sdk-and-tools/erdpy/configuring-erdpy/

Here it seems like the chain id is a version number or something like that. When in reality it's.

Mainnet: 1
Testnet: T
Devnet: D

Thought I would ask first, because maybe I'm misunderstanding something myself :)

**Comment by miiu96** [comment]
Hello. 
Thank you for reporting this. 
This PR should fix this problem https://github.com/ElrondNetwork/docs.elrond.com/pull/138.

**Comment by miiu96** [comment]
Can we close this issue  ?
