### ISSUE TITLE
Make "Networking" its own chapter

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/docs.elrond.com#168]
Currently networking (or open ports) is hidden at the end here:

https://docs.elrond.com/validators/system-requirements/

This should be promoted to its own chapter and updated.

* System administrators installing Elrond nodes will first look at what ports they need to open and this information is hard to find

* It does not describe traffic types (TCP/UDP) and RPC ports - this information should be also included

* UFW command does not make sense `sudo ufw allow 37373:38383/tcp` - why is it like this?

**Comment by bogdan-rosianu** [comment]
Hello! Thank you for opening this issue. I have extended a bit the documentation by adding a note in #405
