### ISSUE TITLE
Testnet faucet is not documented

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/docs.elrond.com#173]
The developer cannot complete any of the tutorials, because they cannot get testnet EGLD.

The documentation does not have any reference to a faucet.

<img width="449" alt="image" src="https://user-images.githubusercontent.com/49922/130316789-2081f9e4-ab8f-483a-a566-33de30445182.png">

The search result does not give any hits.

The link was only available through a Telegram chat room: https://r3d4.fr/elrond/devnet/index.php

<img width="437" alt="image" src="https://user-images.githubusercontent.com/49922/130316762-13fdf55a-b815-44fc-b891-debf54cda2cc.png">

**Comment by bogdan-rosianu** [comment]
Hello! Thank you for opening this issue. I have added docs about the faucet in #405
