### ISSUE TITLE
Validator key generation is not documented

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/docs.elrond.com#175]
Currently the [validator key page](https://docs.elrond.com/validators/key-management/validator-keys/) does not describe how validator keys are supposed to be generated.

Suggestions

* Make the key optionally in the first place if it is not needed: https://github.com/ElrondNetwork/elrond-go/issues/3367

* Web based generator

* Static downloads for `keygenerator` binary 

* Add `erdpy` commands or `bash` shell commands with `openssl` to generate necessary PEM files

* See also https://github.com/ElrondNetwork/elrond-go/issues/3368

**Comment by bogdan-rosianu** [comment]
Thank you for opening this issue! I have added an example on how to use the `keygenerator` in PR #405
