### ISSUE TITLE
ESDT documentation does not discuss name and symbol limitations

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/docs.elrond.com#190]
ESDT documentation does not discuss about string format and limitations.

https://docs.elrond.com/developers/esdt-tokens/#issuance-of-fungible-esdt-tokens

It can be assumed the string encoding is UTF-8. But, for example, is it legit to create a token with a name of 1,000,000 characters?

**Comment by bogdan-rosianu** [comment]
Hello! Thank you for opening this issue. The limitation for the token name/ticker/num decimals are described here:
- https://docs.elrond.com/tokens/esdt-tokens/#parameters-format
