### ISSUE TITLE
Token issuance and magical random number undocumented

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/docs.elrond.com#191]
The token issuance documentation

https://docs.elrond.com/developers/esdt-tokens/

describes

> The contract will add a random string to the ticker thus creating the token identifier. The random string starts with “-” and has 6 more random characters. For example, a token identifier could look like ALC-6258d2.

However, the documentation fails to explain how the issuer will find out what the token identifier he or she has received. There is a random number created, but there is no documentation how to find out what this random number was.

**Comment by bogdan-rosianu** [comment]
Hello! Thank you for your suggestion. The change has been added in #405
