### ISSUE TITLE
ESDT transfer and non-zero value

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/docs.elrond.com#192]
In the ESDT transfer example

https://docs.elrond.com/developers/esdt-tokens/#transfers

We use EGLD value 0 for token transfer and the amount of tokens is encoded separate in `Data` field.

However, the documentation does not describe what should happen in the situations if EGLD value is set to non-zero.

**Comment by bogdan-rosianu** [comment]
Hello! Thank you for opening this issue. I have added a note in PR #405
