### ISSUE TITLE
ESDT token transfer gas limit incorrectly documented

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/docs.elrond.com#193]
In the ESDT transfer example

https://docs.elrond.com/developers/esdt-tokens/#transfers

it says you need to use a gas limit of 250,00 to do an ESDT token transfer transaction. 

This is incorrect and using the gas limit of 250,000 will result in a failed transaction.

<img width="1091" alt="image" src="https://user-images.githubusercontent.com/49922/133307546-d5da3d21-50e4-499d-8563-78fcd9e74782.png">

**Comment by miohtama** [comment]
A value of 500k gas will work instead.

**Comment by bogdan-rosianu** [comment]
Thank you for opening this issue. The documentation has been updated meanwhile.
