### ISSUE TITLE
Available chain ids and their rationale undocumented

### ISSUE THREAD

**Issue by miohtama** [ElrondNetwork/docs.elrond.com#194]
Elrond chain ids are not covered in the documentation

<img width="787" alt="image" src="https://user-images.githubusercontent.com/49922/133308333-ad1166e5-728d-4fc6-a5ef-b2ee1bb2fc19.png">

The information like that `D` means devnet can be uncovered from the source code, but nowhere in the documentation it is not explained what chain ids are available now, how they are chosen, will they stay the same, how to have your own chain id and is it ever needed and so on.

**Comment by bogdan-rosianu** [comment]
Thank you for opening this issue. I have added a note and also included that node in the search results for `chainid`. #405
