### ISSUE TITLE
Add comparison with Solana

### ISSUE THREAD

**Issue by tredondo** [ElrondNetwork/docs.elrond.com#230]
Very good to see the [Detailed comparisons](https://docs.elrond.com/detailed-comparison/overview/)!

Would love to see Solana there, since it's the L1 blockchain with the largest market cap.

**Comment by bogdan-rosianu** [comment]
Hello! Thank you for opening this issue. Actually, we have deleted the detailed comparisons section of the documentation, thus we won't add another.
