### ISSUE TITLE
Add detailed comparison with Kadena

### ISSUE THREAD

**Issue by tredondo** [ElrondNetwork/docs.elrond.com#231]
Very good to see the [Detailed comparisons](https://docs.elrond.com/detailed-comparison/overview/)!

Would love to see Kadena there, since it's the most scalable PoW blockchain (480,000 tps).

**Comment by bogdan-rosianu** [comment]
Hello! Thank you for opening this issue. Actually, we have deleted the detailed comparisons section of the documentation, thus we won't add another.
