### ISSUE TITLE
Rest API: estimate tx cost, missed nonce param

### ISSUE THREAD

**Issue by chvarkov** [ElrondNetwork/docs.elrond.com#452]
Hello, I found missed param `nonce` here [`estimate-cost-of-transaction`](https://docs.elrond.com/sdk-and-tools/rest-api/transactions/#estimate-cost-of-transaction)
It works without `nonce` if `data` is empty. In another cases response will be: txGasUnits=0, returnMessage="lower nonce in transaction".

**Comment by chvarkov** [comment]
I submitted PR to fix it https://github.com/ElrondNetwork/docs.elrond.com/pull/453

**Comment by bogdan-rosianu** [comment]
Thank you for your contribution. The PR has been merged !
